encoding: don't inherit constructors from std::vector
This is a partial revert of commit 5d0b0106dfc7675f9048976d4dd4ea00e46e6c39,
which caused the following build failure with gcc-7:

./libndn-cxx.so: error: undefined reference to 'std::allocator<unsigned char>::allocator()'

Change-Id: I58136eb1901425158e529e37b6fa288b72fc46f6